### ISSUE TITLE
sniffer problem

### ISSUE THREAD

**Issue by darkopetrovic** [mitshell/CC2531#1]
Hello mitshell,

it's working better than the last week :) 

I just tried your the code, and sometimes I've got this error:

```
[ERR] (Layer - <class 'libmich.formats.IEEE802154.TI_CC'>) String buffer not long enough for Correl
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mitshell/CC2531/CC2531/interpreter.py", line 189, in process
    self.interpret(frame)
  File "/opt/mitshell/CC2531/CC2531/interpreter.py", line 198, in interpret
    msg = self._get_tlv(msg)
  File "/opt/mitshell/CC2531/CC2531/interpreter.py", line 231, in _get_tlv
    self._interpret_TV(T, V)
  File "/opt/mitshell/CC2531/CC2531/interpreter.py", line 248, in _interpret_TV
    self._interpret_TI_USB(V)
  File "/opt/mitshell/CC2531/CC2531/interpreter.py", line 257, in _interpret_TI_USB
    usb.map(V)
  File "/usr/local/lib/python2.7/dist-packages/libmich/core/element.py", line 1519, in map
    self.__map_aligned(string)
  File "/usr/local/lib/python2.7/dist-packages/libmich/core/element.py", line 1564, in __map_aligned
    e.map(string)
  File "/usr/local/lib/python2.7/dist-packages/libmich/core/element.py", line 1519, in map
    self.__map_aligned(string)
  File "/usr/local/lib/python2.7/dist-packages/libmich/core/element.py", line 1551, in __map_aligned
    string = self.__map_to_bitstack(string)
  File "/usr/local/lib/python2.7/dist-packages/libmich/core/element.py", line 1600, in __map_to_bitstack
    bit_elt.map_bit( int(s_bin[:bit_elt.bit_len()], 2) )
ValueError: invalid literal for int() with base 2: ''
```

**Comment by mitshell** [comment]
ok, I made a change today that should make it work with less errors.

I would be interested to know what kind of USB frame provided by the dongle lead to such error : USB frames are forwarded over UDP localhost (port 2154), so you could eventually send me a copy of this UDP traffic in case you still encounter bad behavior with the program.

**Comment by darkopetrovic** [comment]
Thank you! The program doesn't stop anymore but the error is still present:

```
[ERR] (Layer - <class 'libmich.formats.IEEE802154.TI_CC'>) String buffer not long enough for Correl
Exception in thread Thread-1:
```

I did the same temporarily in the file "/usr/local/lib/python2.7/dist-packages/libmich/core/element.py".
I can live with it. 

Which program could I use to grap the UDP packets on this port? Because the command 'nc -u -l 2154' tell me the the port is already in use. How could I do it properly?

**Comment by mitshell** [comment]
Hello,

you can use tcpdump from the shell, or wireshark which has a GUI.
netcat is to connect to a network service, not to tap the IO of a given
interface.

Best Regards,
Benoit

2014-09-12 15:05 GMT+02:00 Darko Petrovic notifications@github.com:

**Comment by nikwest** [comment]
I am having the same issue. Once in a while I get the error:

[libmich ERR](Layer - <class 'libmich.formats.IEEE802154.TI_CC') String buffer not long enough for Correl

I'll see if I can send you a dump.

**Comment by mitshell** [comment]
This means the format of the 802.15.4 frame produced by the dongle does not correspond to what is expected by the "interpreter" part (which decodes the 802.15.4 frame and print it on screen). Does the application crash ? Or does it only print the error message about the decoding ?

I never had this kind of error on my side, hence I will need a trafic dump if you want me to analyze the issue and possibly change the application.
