### ISSUE TITLE
Sniffer exits when initializing

### ISSUE THREAD

**Issue by BramBonne** [mitshell/CC2531#4]
When trying to initialize the sniffer, it exits with the following error:

```
[GPS_reader][ERR] cannot open /dev/ttyUSB0
[CC2531][17664] driving CC2531 USB Dongle @ USB bus 2 & address 7, with serial 17664
Traceback (most recent call last):
  File "CC2531/sniffer.py", line 255, in <module>
    main()
  File "CC2531/sniffer.py", line 240, in main
    ccs = prepare_receiver(chans)
  File "CC2531/sniffer.py", line 123, in prepare_receiver
    ss = [receiver(cc) for cc in ccs]
  File "/home/bram/Progs/CC2531/CC2531/receiver.py", line 101, in __init__
    self._cc.init()
  File "/home/bram/Progs/CC2531/CC2531/CC2531.py", line 232, in init
    self._set_config(0)
  File "/home/bram/Progs/CC2531/CC2531/CC2531.py", line 182, in _set_config
    ret = self.com.controlWrite(0x00, 9, c, 0, 0)
  File "build/bdist.linux-x86_64/egg/usb1.py", line 1307, in controlWrite
TypeError: object of type 'int' has no len()
```

This is using Python version `2.7.11`, with both libusb and libmich at the latest git version.

**Comment by BramBonne** [comment]
The problem seemed to be with the installed version of libusb; if installed with `pip` everything seems to work fine.

**Comment by mitshell** [comment]
Thanks for reporting.
